apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-qa
  labels:
    env: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-qa
  template:
    metadata:
      labels:
        app: myapp-qa
    spec:
      containers:
        - name: myapp
          image: docker.io/myuser/my-app:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-qa-service
spec:
  selector:
    app: myapp-qa
  ports:
    - port: 80
      targetPort: 5000
  type: NodePort    
